#!/usr/bin/env bash
# shellcheck disable=SC2154
# This script configures Nginx so that its HTTP response contains a custom
# header.

sudo apt update
sudo apt install nginx -y
sudo sed -i "20i\        add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
